### ISSUE TITLE
Simulation 3&4 produce conflicts that need total order

### ISSUE THREAD

**Issue by RubbyRedson** [victor-axelsson/id2210#18]
We have implemented most of the functionality specified in the paper but we have some issues with one of the examples from the paper. Fig3 from the paper (see appended image).

Output from node1:

- {"doc":{"grocery":["[0]":"eggs","[1]":"ham","[2]":"milk","[3]":"flour"]}}

Output from node2:
- {"doc":{"grocery":["[0]":"milk","[1]":"flour","[2]":"eggs","[3]":"ham"]}}

The causality is preserved and the operations are concurrent (as specified in the paper) but as you can see it's not totally ordered. The paper suggests the following: 

   "There is no information on which replica’s items should appear first in the merged result, so the algorithm can make an arbitrary choice between “eggs, ham, milk, flour” and “milk, flour, eggs, ham”, provided that all replicas end up with the items in the same order. "

It turns out that this is majorly complicated for us to accomplish. 
<img width="882" alt="skarmavbild 2017-05-23 kl 16 23 53" src="https://cloud.githubusercontent.com/assets/3581469/26359776/a2f48318-3fd6-11e7-972f-55e5f265f44b.png">

**Comment by victor-axelsson** [comment]
This now works
