### ISSUE TITLE
Simluation

### ISSUE THREAD

**Issue by victor-axelsson** [victor-axelsson/id2210#6]
# About
We should start doing some simulations from the Java app. First we can start with a simple simulation where one client adds an item to the doc and then make sure that the other gets it. 

# How to simulate
I think we should use the scenarios given in the paper to simulate that we can do the same, and checking for all these issues with concurrency that you can get.

I'm not gonna paste all in here but I mean these: 
<img width="808" alt="skarmavbild 2017-05-18 kl 13 39 11" src="https://cloud.githubusercontent.com/assets/5947764/26200654/6edbc042-3bcf-11e7-9565-df72e15ee53d.png">

**Comment by victor-axelsson** [comment]
I have a simulation architecture up (it's in simulation branch). But it doens't want to cooperate with java->scala.

**Comment by RubbyRedson** [comment]
Java - Scala problem seems to be because of version mismatch that happens because of default scala plugin version

**Comment by RubbyRedson** [comment]
Simulation architecture is finished and running
